"""add added_on to twig table

Revision ID: 74a5557162c1
Revises: 780f2a5edea1
Create Date: 2020-01-20 14:37:19.391111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "74a5557162c1"
down_revision = "780f2a5edea1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "twigs",
        sa.Column("added_on", sa.TIMESTAMP(timezone=True), nullable=False),
    )
    op.create_index(
        op.f("ix_twigs_added_on"), "twigs", ["added_on"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_twigs_added_on"), table_name="twigs")
    op.drop_column("twigs", "added_on")
    # ### end Alembic commands ###
